# Generated by Django 5.0.10 on 2026-02-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='almaty', max_length=32)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('high', 'High risk')], default='normal', max_length=16)),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult'), ('elderly', 'Elderly')], default='adult', max_length=16)),
                ('asthma_flag', models.BooleanField(default=False)),
                ('other_resp_flag', models.BooleanField(default=False)),
                ('activity', models.CharField(choices=[('indoor', 'Mostly indoor'), ('commute', 'Commute'), ('outdoor_work', 'Outdoor work'), ('outdoor_sport', 'Outdoor sport')], default='commute', max_length=16)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('kk', 'Қазақша')], default='ru', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
